### ISSUE TITLE
发版不符合语意化要求

### ISSUE THREAD

**Issue by Viggo95** [LancerComet/vue2-jsx-runtime#5]
## 背景&问题
看到 `@lancercomet/vue2-jsx-runtime` 最新 latest 版本是 **`0.3.0-test.0`**

## 如何复现

``` shell
npm info @lancercomet/vue2-jsx-runtime
```

<img width="247" alt="image" src="https://user-images.githubusercontent.com/22092110/177933318-ba3c6a2c-1344-413c-a151-c8fca137ca19.png">

## 期望方案

- latest tag 不应该携带 `-test.0` 这样的后缀，应该是一个 `major. minor. patch`
- 可以是 `0.3.1`

**Comment by LancerComet** [comment]
https://www.npmjs.com/package/@lancercomet/vue2-jsx-runtime

latest 是 0.3.0，这个版本是不是镜像仓库，先用一下 npm

**Comment by Viggo95** [comment]
ok，看起来是公司内部源没能正确拉到最新版本，我自己手动更新一下，issue属于误报🙏，我先 close

<img width="800" alt="image" src="https://user-images.githubusercontent.com/22092110/177961584-aa04caac-0202-4741-8c38-ca6726b01b96.png">
